### ISSUE TITLE
Proposal: refactor task module to use terraform names

### ISSUE THREAD

**Issue by nathanielks** [segmentio/stack#117]
Currently the [task](https://github.com/segmentio/stack/blob/master/task/main.tf#L108-L110) module outputs a variable called `name`, which refers to `aws_ecs_task_definition.main.family`. To keep things consistent with terraform's naming convention, how would you feel about the output being renamed to `family` instead of `name`?

**Comment by achille-roussel** [comment]
I like the consistency but unfortunately this is a non-backward compatible change so there's a chance it would break someone's code.

I also think the "family" term makes sense because ECS allows multiple containers to be described in a single task definition but the stack module only supports defining one container, so I don't feel too bad about having it be "name".

**Comment by nathanielks** [comment]
Aye aye, @achille-roussel 👍 

Another option is output both for back-compat as well as the option of using `family`?

**Comment by achille-roussel** [comment]
It's an option but I'd rather have a single name to avoid any confusion coming from reading code that would sometimes use "name" and sometimes "family".

**Comment by nathanielks** [comment]
💯
